name = input("Please enter your name: ")
print("Your name is",name)
x=input("Enter first number:")
y=input("Enter second number:")
print(x+y)
print(int(x)+int(y))
# print(x-y)
print(int(x)-int(y))
# print(x*y)
print(int(x)*int(y))
# print(x/y)
print(int(x)/int(y))