# Unique Number Collector Using Sets in Python
unique=set()
n=int(input("Enter the number 1:"))
unique.add(n)
n=int(input("Enter the number 2:"))
unique.add(n)
n=int(input("Enter the number 3:"))
unique.add(n)
n=int(input("Enter the number 4:"))
unique.add(n)
n=int(input("Enter the number 5:"))
unique.add(n)
n=int(input("Enter the number 6:"))
unique.add(n)
print(f"The unique numbers are:{unique}")